### ISSUE TITLE
Bug: Segment zaraz integration - "track" api mapping

### ISSUE THREAD

**Issue by maxkna111** [managed-components/segment#1]
hi there, 
i have managed to hook zaraz with segment and mapped tracking events to segment
but i found out tracking events specifically don't show up in the dashboard at all.. 
after some further research i found out the exact reason and bug in this repo:
https://github.com/managed-components/segment/blob/main/src/index.ts#L19

the line 
```typescript
    ...(payload.event && { event }),
```
is the wrong way to send the event name to segment, since segment expect this as a string 
not an object with this interface

```typescript
interface MCEvent {
  readonly name?: string
  readonly payload: any
  client: Client
  readonly type: string
}
```

segment docs clearly states the "event" property should be a string for HTTP API source
https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#track

here is an example of what is actually sent right now from zaraz
```json
{
    "event": {
        "name": "Signout success",
        "type": "track",
        "payload": {
            "userId": null,
            "anonymousId": null,
            "previousId": null,
            "event": "Signout success"
        },
        "client": {
            "url": "<URL_HERE>",
            "title": "<title>",
            "timestamp": 1684148411,
            "timezoneOffset": -180,
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0",
            "screenWidth": 1920,
            "screenHeight": 1200,
            "viewportWidth": 1075,
            "viewportHeight": 964,
            "language": "en",
            "referer": "",
            "ip": "<IP_HERE>",
            "emitter": "browser"
        }
    },
    "callType": "track",
    "anonymousId": "<gen_id>",
    "userId": null,
    "context": {
       ...
    },
    "properties": {
        "userId": null,
        "anonymousId": null,
        "previousId": null,
        "event": "<event_name"
    }
}
```

although segment returns a `{success:true}` nothing shows up in their dashboard for any of the tracking events
notice the context (abbreviated) and "event.client" contain the same value and this confirms that this is definitely not intentional 
another note is that the "event name" prop is only necessary for events of type "track" but the UI in cloudflare shows it as required for all types e.g. page view and identify... which is not the case

**Comment by bjesus** [comment]
Thank you @nazihahmed for reporting this! @tomkln will take a look shortly.
